# Base configs
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"

# UI configs
title: "Gordon's Gallery "
subtitle: "Random Photographs"
author:  "gordon"
header:
 title: "Street Shots"
 subtitle: ""
footer:
 name: "Gordon"
 bio: "Amateur camera-wrangler, all photographs (c)."
social_urls:
  instagram: "https://www.instagram.com/gordonw_str/"
