# Base configs
baseurl: "https://gordonrgw.github.io"
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
google_analytics: ""

# UI configs
title: "Photography by Gordon"
subtitle: "See the world through my eyes!"
author: "gordon"
header:
 title: "Photography"
 subtitle: "by gordon"
footer:
 name: "Hey there, my name is Ram"
 bio: "Amateur camera hacker."
 github: ""
web_design: "AJ"
social_urls:
  instagram: "https://www.instagram.com/gordonw_str"
  
